### ISSUE TITLE
xframe and prepare() give different catB for high-cardinality predictor when NAs present

### ISSUE THREAD

**Issue by markwh** [WinVector/vtreat#29] opened 2021-03-03 22:22 UTC
In certain situations a catB encoded high-cardinality predictor is significantly different between training data (from the crossframe) and testing data (from prepare). 

I encountered this problem "in the wild", but the following example reproduces it. It seems like the crossvalidation folds are lumping the level into "rare" in the crossframe, but not the treatment itself. This only seems to happen for sufficiently large cardinality and missingness and for level counts near the `rareCount` value, but I haven't been able to determine exactly what triggers it.

``` r
library(vtreat)
#> Loading required package: wrapr

set.seed(2311)
nsim <- 10000 # nrow of traning data
rareCount <- 180 # passed to mcCrossFrameCExperiment()
nlvl1 <- 200 # This many occurances of "lvl1" factor level
p1 <- 0.9 # outcome prob when predvar == "lvl1"
p2 <- 0.5 # outcome prob when predvar != "lvl1"
n_na <- 800 # This many missing values in predictor
otherlevels <- paste0("lvl", 2:50)

traindf <- data.frame(
  outcome = c(
    sample(c("Y", "N"), nlvl1, replace = TRUE, prob = c(p1, 1 - p1)),
    sample(c("Y", "N"), nsim, replace = TRUE, prob = c(p2, 1 - p2))
    ),
  predvar = c(
    rep("lvl1", nlvl1), 
    rep(NA_character_, n_na),
    sample(otherlevels, nsim - n_na, replace = TRUE)
))
testdf <- data.frame(predvar = "lvl1")

xf <- mkCrossFrameCExperiment(traindf, "predvar", "outcome", "Y", 
                              rareCount = rareCount)
#> [1] "vtreat 1.6.2 start initial treatment design Wed Mar  3 17:06:29 2021"
#> [1] " start cross frame work Wed Mar  3 17:06:30 2021"
#> [1] " vtreat::mkCrossFrameCExperiment done Wed Mar  3 17:06:31 2021"

unique(xf$crossFrame$predvar_catB[1:(nlvl1)])
#> [1] 0.008405523 0.021683092 0.006087083
prepare(xf$treatments, testdf)$predvar_catB # much different from training value
#> [1] 2.028887
```

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by JohnMount** [comment] 2021-03-03 22:32
Thank you for the note and the detailed, and good, run down.

At a top level, this is an intended consequence of the cross-frame experiment setup. Without the additional cross-validation the catB variables would themselves be over-fit and a source of data leaks, degrading downstream modeling steps. An example where the over-fit is a problem is given here: https://github.com/WinVector/vtreat/blob/main/Examples/KDD2009/KDD2009Example.md 

At a finer level: the internal vtreat cross validation potentially makes different inconsistent decision on each cross-fold. What is rare and not rare can differ a bit in each fold. So one does get different levels either qualifying or not qualifying for different steps. This is, of course, the undesirable end of this.

If one wants the same transform on training and test (and in most cases one does not, as it doesn't lead to the same performance on training and test) one can use `designTreatmentsC` instead of `mkCrossFrameCExperiment.

I'll try and look later to see if the example is expected on unexpected behavior.

**Comment by markwh** [comment] 2021-03-04 02:35
Would it not be desirable to choose the "rare" grouping based on the entire training set, across all folds? I can't see how that would leak any information about P(Y|X)

**Comment by JohnMount** [comment] 2021-03-04 02:46
Likely yes. Probably any determinations that are a function of the explanatory variables alone should be made consistent across all folds.

**Comment by JohnMount** [comment] 2021-06-11 14:37
I'm going to close this as "won't fix." The design of R vtreat is to treat the folds as very independent and engineering around that is going to be fighting that organization. I believe the Python vtreat was designed to treat the cross-folds as a bit more related, so effects like this are a bit easier to control in that version.

Also there are some subtle points as what leaks info about P(Y|X) to which observer. An observer that is pre-informed that rare levels are dependent on Y may have a different desired outcome that one that doesn't. Obviously the package does use "didn't see Y" as a stand-in for not leaking P(Y|X), or it can't have any shared calculations. But there are some subtle points.

I am hoping the detriment is not that strong an overcome with larger data sets.

**Closed by JohnMount** 2021-06-11 14:37 UTC
Labels: enhancement
