### ISSUE TITLE
Factor treatment designTreatmentsC

### ISSUE THREAD

**Issue by rsuhada** [WinVector/vtreat#1] opened 2016-04-18 13:41 UTC
Thank you for the nice package!
I've just went through the initial tutorial and noticed (and fully reproduced) an odd result in:

https://winvector.github.io/vtreathtml/vtreat.html

After applying the treatment from designTreatmentsC, we test
1. mean of all predictors is 0
2. slope of lin. fit is 1

Neither of these is true for x_lev_x.b:
mean is 3.333333e-01
slope is -1.442222e-16

For all the other variables as well as for everything in designTreatmenN example it all seems OK.

Is this an expected behavior?
Oddly the x_lev_x.b is coded with 0s and 1s, while other variables are fractional. 

Thank you very much!

**Comment by JohnMount** [comment] 2016-04-18 15:29
rsuhada,

Thanks for your issue.  I definitely see the problem you are talking about.  To repeat: the issue is as in the vtreat.html example we process data as follows:

library('vtreat')
dTrainC <- data.frame(x=c('a','a','a','b','b',NA),
   z=c(1,2,3,4,NA,6),
   y=c(FALSE,FALSE,TRUE,FALSE,TRUE,TRUE))
treatmentsC <- designTreatmentsC(dTrainC,colnames(dTrainC),'y',TRUE)
prepare(treatmentsC,dTrainC,pruneSig=c(),scale=TRUE)

And (contrary to the claims in the document the derived variable x_lev_x.b is not scaled and doesn't meet the expected scaled claims (mean zero and slope 1 when regressed with y).

It looks like the issue that the conditional distribution of y|x_lev_x.b is equal to the base distribution of y and also equal to the complementary distribution y|!x_lev_x.b.  This means variable x_lev_x.b is perfectly independent of y.  So the scaling slope would have to be zero (which it is).  It looks like the code detected this exceptional condition and skipped scaling on this variable (instead of writing NA, throwing or skipping the variable).  So we would not see this variable if we had pruned with pruneSig<1.  I am guessing the best the library can do is get the mean to zero (why not) and fix the documentation/example on this one.

Sorry about sowing a bit of confusion there.  We will incorporate a fix today.

**Comment by JohnMount** [comment] 2016-04-18 17:15
rsuhada,

Thanks for your issue report!

I have pushed a fix to the dev version of vtreat ( https://github.com/WinVector/vtreat ).  I have also fixed some documentation, added a test (to try and catch any reversion), and produced a vignette explaining the nuance of the issue: http://winvector.github.io/vtreathtml/vtreatScaleMode.html

**Closed by JohnMount** 2016-04-18 17:15 UTC
