### ISSUE TITLE
vtreat mkCrossFrameNExperiment efficiency

### ISSUE THREAD

**Issue by EKtheSage** [WinVector/vtreat#17] opened 2018-06-22 15:16 UTC
Hello,

Do you have a rough estimate of how much time it takes to run the design treatments? I have a data frame of about 400K rows x 25 cols and it takes almost an hour to run the cross frame experiment and I want to know if that's the normal time of treating a data frame of this size. If this is normal then could there be ways to improve the run time?

Thanks,

Ethan

**Comment by JohnMount** [comment] 2018-06-22 16:04
Ethan,

Sorry you are having trouble. And thank you for taking the time to file an issue.

That sounds slow to me (especially after the sampling fix @khotilov contributed and some parallel fixes). Please make sure you are on the latest version of `vtreat` and that you have `data.table` installed (it is now used for fast row binding).  Also `vtreat` will accept a parallel cluster to speed up work.

I can take a look at timing on my end.  All I would need to know is the following rough description of your data set: how many rows (you said around 400,000), how many numeric columns, how many categorical columns, and the number of unique values in each of the categorical columns.  Also is the outcome you are predicting numeric (a regression task) or categorical (a classification task)?

John

**Comment by JohnMount** [comment] 2018-06-22 17:12
I now have some timings and best-practices [here](https://github.com/WinVector/vtreat/blob/master/extras/TimingExample.md).  I think a job of the scale you are describing should take under 10 minutes with moderate use of parallel (just using an old Mac-Mini with 4 cores, so that is consistent with about 40 minutes without use of parallel).

**Comment by EKtheSage** [comment] 2018-06-22 17:42
Hello John,

The table has 25 columns, but only 12 predictors, the rest of the columns are either IDs or response.  Of the 12 predictors, 9 are categorical and 3 are numeric. I am doing a regression task. The table has 411426 rows, to be exact.

I use data.table for my data manipulation tasks but I haven't tried parallel vtreat yet. I will look into that.

Ethan

**Comment by EKtheSage** [comment] 2018-06-22 17:48
That's a really good example, John. I also realized my vtreat version was 1.0.1, so I just updated that to 1.2.0. Will let you know if I am still experiencing slow run time with the new version and parallel run.

**Comment by JohnMount** [comment] 2018-06-22 18:09
No problem `1.2.0` is very new (just this week).  We are switching our work over to `data.table` and using it in more of our packages.  Also I need to be able to answer precise questions such as yours: "how long does one expect something of this scale to take?"

**Comment by EKtheSage** [comment] 2018-06-22 20:20
OK, here are the results of running on single core vs multi core (48) I don't see much improvement with using multicore (maybe 1 minute faster?). However, vtreat version 1.2.0 helps improve the design treatment as the run time is cut down to about 20 minutes instead of 60 minutes before.

single core

```
[1] "vtreat 1.2.0 start initial treatment design Fri Jun 22 13:56:19 2018"
[1] " start cross frame work Fri Jun 22 14:09:30 2018"
[1] " vtreat::mkCrossFrameNExperiment done Fri Jun 22 14:18:02 2018"
```


multi core

```
[1] "vtreat 1.2.0 start initial treatment design Fri Jun 22 15:10:00 2018"
[1] " start cross frame work Fri Jun 22 15:22:23 2018"
[1] " vtreat::mkCrossFrameNExperiment done Fri Jun 22 15:31:02 2018"
```

**Comment by JohnMount** [comment] 2018-06-22 21:49
Wow, looks like the multi-core is doing nothing for you (sorry).  Probably not enough columns to parallelize on.  20 minutes is a long time, but better than 60 minutes.

**Comment by JohnMount** [comment] 2018-06-23 18:18
I am going to go ahead and close this issue. It isn't as fast as I want, but it looks like we have picked up a 3x speed increase in the 1.x series of `vtreat`.  I'll try to get more performance patches in as we go, and please feel free to open a new issue if you find an acute performance problem.

**Comment by JohnMount** [comment] 2018-06-24 16:16
I am re-opening this issue.  In July I plan to experiment on an option to parallelize over cross-validation replications instead of parallelizing over columns.  That may be what would speed up an example of the size you are working with.

**Comment by JohnMount** [comment] 2018-06-25 00:13
Also a note.  `vtreat` currently does not use the default or registered parallel cluster, you have to pass it the cluster as an argument to get it to use it.  I'll probably fix that in the next version.

**Comment by JohnMount** [comment] 2018-06-28 13:37
Re-closing this issue in favor of one specific todo: use the default parallel cluster.

**Closed by JohnMount** 2018-06-28 13:37 UTC
